import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { openPanel, closePanel } from './panels';

test('teaching links the card, recorded map targets and keyboard timeline without advancing inspection time', async ({ page }) => {
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  await page.goto('/');
  await page.getByRole('checkbox', { name: 'Teaching mode', exact: true }).check();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.runFor(100);
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Teaching pause');
  await expect(page.getByLabel('Current action', { exact: true })).toHaveText('Choice held before execution');
  await expect(page.getByRole('region', { name: 'Latest decision' })).toContainText('#1 · 00:00');
  const marker = page.getByRole('button', { name: /Inspect decision 1 target .*Selected/ }).first();
  await expect(marker).toBeAttached();
  await marker.click();
  await expect(page.getByLabel('Decision 1 details')).toBeVisible();
  await closePanel(page);
  await page.clock.fastForward(60_000);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
  await page.getByRole('button', { name: 'Continue selected action', exact: true }).click();
  await page.clock.fastForward(30_000);
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Teaching pause');
  const time = await page.getByLabel('Remaining expedition time').textContent();
  const history = page.getByRole('button', { name: /^Inspect decision 1 at/ });
  await history.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Manual inspection');
  await expect(page.getByRole('region', { name: 'Latest decision' })).toContainText('Historical decision selected');
  await expect(page.getByLabel('Decision map context')).toContainText('Decision 1 · 00:00');
  await expect(page.getByLabel('Decision 1 details')).toContainText('Battery 160.0 / 160');
  await expect(page.getByRole('checkbox', { name: 'Full-world debugging view' })).toBeDisabled();
  await page.getByRole('button', { name: 'Follow rover', exact: true }).click();
  await page.clock.fastForward(60_000);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText(time!);
  await page.screenshot({ path: 'test-results/decision-history-desktop.png' });
  await page.keyboard.press('Escape');
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Teaching pause');
  await page.getByRole('button', { name: 'Continue selected action', exact: true }).click();
  await page.clock.runFor(100);
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Code executing');
});

test('a saved teaching expedition replays one choice at a time without new inference', async ({ page }) => {
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  await page.goto('/');
  await page.getByRole('checkbox', { name: 'Teaching mode', exact: true }).check();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.getByRole('button', { name: 'Continue selected action' }).click();
  await page.clock.fastForward(30_000);
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  await openPanel(page, 'Saved expeditions');
  await page.getByRole('button', { name: /Open expedition/ }).click();
  let calls = 0;
  await page.route('**/api/**', route => { calls++; return route.abort(); });
  await page.getByRole('button', { name: 'Replay expedition', exact: true }).click();
  const replay = page.getByRole('region', { name: 'Expedition replay' });
  await replay.getByRole('checkbox', { name: 'Replay teaching mode' }).check();
  await replay.getByRole('button', { name: 'Restart replay' }).click();
  await expect(replay.getByRole('button', { name: 'Continue recorded action' })).toBeVisible();
  await page.clock.fastForward(60_000);
  await expect(replay.getByLabel('Replay elapsed time')).toHaveText('00:00');
  await replay.getByRole('button', { name: 'Continue recorded action' }).click();
  await page.clock.fastForward(60_000);
  await expect(replay.getByRole('button', { name: 'Continue recorded action' })).toBeVisible();
  await expect(replay.getByLabel('Replay elapsed time')).toHaveText('00:04');
  await replay.getByRole('button', { name: 'Continue recorded action' }).click();
  await expect(replay.getByRole('status')).toHaveText('Replay complete');
  expect(calls).toBe(0);
});

test('a pending Jev response settles during inspection without resuming, and its wait target is linked to evidence', async ({ page, request }) => {
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  let submissions = 0;
  page.on('request', request => { if (request.url().endsWith('/api/decision')) submissions++; });
  await page.goto('/');
  await openPanel(page, 'Mission');
  await page.getByRole('combobox', { name: 'Expedition controller' }).selectOption('typesafe');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  const card = page.getByRole('region', { name: 'Latest decision' });
  await expect(card).toContainText('Wait · 5 seconds');
  await openPanel(page, 'Mission');
  await page.getByRole('textbox', { name: 'Mission instructions' }).fill('Hold for browser verification');
  await page.getByRole('button', { name: 'Apply instructions' }).click();
  await closePanel(page);
  await page.clock.fastForward(5000);
  await expect(card).toContainText('Previous completed choice · History');
  await page.getByRole('button', { name: /^Inspect decision 1 at/ }).click();
  await request.post('http://127.0.0.1:4174/release');
  await expect(page.getByLabel('Current action', { exact: true })).toHaveText('Choice held before execution');
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Manual inspection');
  await page.clock.runFor(100);
  await expect(page.getByRole('button', { name: /Inspect decision 1 target .*Selected wait · Rover/ })).toBeAttached();
  await expect(page.getByRole('table', { name: 'Available actions' })).toContainText('Returned probability');
  await expect(page.getByLabel('Decision 1 details')).toContainText('$0.00004200 USD');
  await page.clock.fastForward(60_000);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('17:55');
  expect(submissions).toBe(2);
  await closePanel(page);
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.runFor(100);
  await expect(page.getByLabel('Current action', { exact: true })).toContainText('Wait');
  expect(submissions).toBe(2);
});

test('a teaching pause retains the usage guard and recovery controls while inspecting', async ({ page }) => {
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  await page.goto('/');
  await page.getByRole('checkbox', { name: 'Teaching mode', exact: true }).check();
  await openPanel(page, 'Mission');
  await page.getByRole('combobox', { name: 'Expedition controller' }).selectOption('typesafe');
  await openPanel(page, 'Usage & recovery');
  await page.getByRole('spinbutton', { name: 'Provider-attempt limit', exact: true }).fill('1');
  await page.getByRole('button', { name: 'Apply inference limits' }).click();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Usage paused');
  await expect(page.getByRole('button', { name: 'Continue selected action' })).toBeDisabled();
  await page.getByRole('button', { name: 'Inspect decisions', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review recovery' })).toBeVisible();
  await closePanel(page);
  await expect(page.getByRole('button', { name: 'Continue selected action' })).toBeDisabled();
  await page.getByRole('button', { name: 'Review recovery' }).click();
  await expect(page.getByRole('region', { name: 'Inference usage pause' })).toContainText('Provider-attempt limit reached');
  await page.clock.fastForward(60_000);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
});

test.describe('narrow decision inspection', () => {
  test.use({ viewport: { width: 390, height: 844 }, hasTouch: true });
  test('touch selection, teaching continuation and cameras remain reachable', async ({ page }) => {
    await page.clock.install();
    await page.clock.pauseAt(new Date());
    await page.goto('/');
    await page.getByRole('checkbox', { name: 'Teaching mode', exact: true }).tap();
    await page.getByRole('button', { name: 'Start expedition' }).tap();
    await page.clock.runFor(100);
    await page.getByRole('button', { name: /^Inspect decision 1 at/ }).tap();
    await expect(page.getByLabel('Decision map context')).toContainText('Recorded knowledge');
    await expect(page.getByLabel('Decision 1 details')).toBeVisible();
    await page.getByRole('button', { name: 'Follow rover', exact: true }).tap();
    await page.clock.runFor(100);
    await page.clock.fastForward(60_000);
    await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
    await expect(page.getByRole('button', { name: 'Stop expedition' })).toBeInViewport();
    await expect(page.getByRole('checkbox', { name: 'Teaching mode', exact: true })).toBeInViewport();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/decision-history-mobile.png' });
    await closePanel(page);
    await page.getByRole('button', { name: 'Continue selected action' }).tap();
    await page.clock.runFor(100);
    await expect(page.getByLabel('Decision phase', { exact: true })).toHaveText('Code executing');
  });
});

test('legacy recharge targets and unavailable evidence remain inspectable and export unchanged without inference', async ({ page }) => {
  const source = await readFile('tests/fixtures/legacy-cadence-v6.json', 'utf8');
  const record = JSON.parse(source);
  const recharge = record.decisions.find((item: { action?: { kind: string } }) => item.action?.kind === 'recharge');
  expect(recharge).toBeTruthy();
  let calls = 0;
  await page.route('**/api/**', route => { calls++; return route.abort(); });
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  await page.goto('/');
  await openPanel(page, 'Saved expeditions');
  await page.getByLabel('Import expedition JSON').setInputFiles({ name: 'legacy.json', mimeType: 'application/json', buffer: Buffer.from(source) });
  const saved = page.getByRole('region', { name: 'Saved expedition', exact: true });
  await saved.locator('summary').filter({ hasText: `Decision ${recharge.id} ·` }).click();
  await page.clock.runFor(100);
  await expect(saved.getByRole('button', { name: new RegExp(`Inspect decision ${recharge.id} target .*Selected recharge · Base`) })).toBeAttached();
  await expect(saved.getByRole('table', { name: 'Available actions' })).toContainText('Unavailable');
  const download = page.waitForEvent('download');
  await saved.getByRole('button', { name: 'Export expedition JSON' }).click();
  expect(JSON.parse(await readFile((await (await download).path())!, 'utf8'))).toEqual(record);
  expect(calls).toBe(0);
});
