import { openPanel, closePanel } from './panels';
import { expect, test } from '@playwright/test';

test('mission control watches a 3D baseline expedition, orbits while paused, and finishes', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'RoverLab' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start expedition' })).toBeVisible();
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  await expect(scene.locator('canvas')).toBeVisible();
  await expect(page.getByText('Base · 01')).toBeVisible();
  await expect(page.getByText('Rover · 01', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
  await page.screenshot({ path: 'test-results/expedition-ready.png', fullPage: true });
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.runFor(1_000);
  await expect(page.getByLabel('Current action')).toContainText('Frontier');
  await expect(page.getByLabel('Rover coordinates')).not.toHaveText('16.00 / 24.00');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  const pausedTime = await page.getByLabel('Remaining expedition time').textContent();
  const pausedPosition = await page.getByLabel('Rover coordinates').textContent();
  const box = (await scene.locator('canvas').boundingBox())!;
  const beforeOrbit = await scene.screenshot();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 170, box.y + box.height / 2 + 70, { steps: 12 });
  await page.mouse.up();
  await page.clock.runFor(1_000);
  expect(await scene.screenshot()).not.toEqual(beforeOrbit);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText(pausedTime!);
  await expect(page.getByLabel('Rover coordinates')).toHaveText(pausedPosition!);
  await page.getByRole('button', { name: '2×', exact: true }).click();
  await expect(page.getByRole('button', { name: '2×', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '4×', exact: true }).click();
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(271_000);
  await expect(page.getByRole('heading', { name: 'Time budget reached' })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('00:00');
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
  await expect(page.getByLabel('Rover coordinates')).toHaveText('16.00 / 24.00');
  await expect(page.getByRole('button', { name: '1×', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  await expect(page.getByRole('heading', { name: 'Stopped by mission control' })).toBeVisible();
  await page.screenshot({ path: 'test-results/expedition.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('the scene reveals discoveries, distinguishes memory, and hides them again on reset', async ({ page }) => {
  await page.clock.install();
  await page.goto('/');
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  await expect(scene.locator('canvas')).toBeVisible();
  await expect(page.getByLabel('Terrain discovered')).toHaveText('29 / 1596 cells');
  await expect(page.getByLabel('Samples discovered')).toHaveText('0');
  await expect(scene.getByText(/Sample [ABC]/)).toHaveCount(0);
  const beforeDiscovery = await scene.screenshot();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(10_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(scene.getByText('Sample A · In range', { exact: true })).toBeVisible();
  await expect(scene.getByText(/Sample [BC]/)).toHaveCount(0);
  await expect(page.getByLabel('Samples discovered')).toHaveText('1');
  await expect(page.getByLabel('Terrain discovered')).not.toHaveText('29 / 1596 cells');
  expect(await scene.screenshot()).not.toEqual(beforeDiscovery);
  await page.screenshot({ path: 'test-results/perception-discovery.png', fullPage: true });
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(90_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(scene.getByText(/Sample A/)).toHaveCount(0);
  await expect(page.getByLabel('Sample A observation')).toContainText('Delivered');
  await expect(scene.getByText('Base · 01 · Remembered', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/perception-memory.png', fullPage: true });
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Terrain discovered')).toHaveText('29 / 1596 cells');
  await expect(page.getByLabel('Samples discovered')).toHaveText('0');
  await expect(scene.getByText(/Sample [ABC]/)).toHaveCount(0);
});

test('mission control selects objectives, sees inspection and cargo, and scores delivery', async ({ page }) => {
  await page.clock.install();
  await page.goto('/');
  const objective = page.getByRole('combobox', { name: 'Scientific objective' });
  for (const [value, sample] of [['past-water', 'A'], ['unusual-minerals', 'B']] as const) {
    await openPanel(page, 'Mission');
    await objective.selectOption(value!);
    await page.getByRole('button', { name: 'Start expedition' }).click();
    await openPanel(page, 'Mission');
    await expect(objective).toBeDisabled();
    await page.clock.fastForward(17_000);
    await expect(page.getByLabel('Current action')).toContainText('Inspect · Sample A');
    await openPanel(page, 'Evidence');
    await expect(page.getByRole('region', { name: 'Discovery progress' }).getByText('Properties unknown · Inspection required')).toBeVisible();
    await expect(page.getByLabel('Samples inspected')).toHaveText('0');
    await page.clock.fastForward(6_000);
    await openPanel(page, 'Evidence');
    await expect(page.getByRole('region', { name: 'Discovery progress' }).getByText(/Layered sediment/)).toBeVisible();
    await expect(page.getByLabel('Samples inspected')).toHaveText('1');
    if (value === 'unusual-minerals') {
      await expect(page.getByLabel('Current action')).toContainText('Explore');
      await expect(page.getByLabel('Cargo capacity')).toHaveText('0 / 2');
      await page.clock.fastForward(64_000);
      await expect(page.getByLabel('Samples inspected')).toHaveText('2');
    }
    await expect(page.getByLabel('Current action')).toContainText(`Collect · Sample ${sample}`);
    await page.clock.fastForward(4_000);
    await expect(page.getByLabel('Cargo capacity')).toHaveText('1 / 2');
    await expect(page.getByLabel('Science score', { exact: true })).toHaveText('0');
    await expect(page.getByLabel('Current action')).toHaveText('Return to base');
    await expect(page.getByRole('region', { name: 'Planetary scene' }).getByText(`Sample ${sample}`, { exact: true })).toHaveCount(0);
    await page.clock.fastForward(value === 'past-water' ? 16_000 : 56_000);
    await expect(page.getByLabel('Cargo capacity')).toHaveText('0 / 2');
    await expect(page.getByLabel('Science score', { exact: true })).toHaveText('10');
    await expect(page.getByLabel(`Sample ${sample} observation`)).toContainText('Delivered');
    await page.getByRole('button', { name: 'Stop expedition' }).click();
    await expect(page.getByRole('region', { name: 'Expedition results' })).toContainText('10 science points');
    await openPanel(page, 'Mission');
    await expect(objective).toBeDisabled();
    await page.screenshot({ path: `test-results/science-${value}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Reset expedition' }).click();
    await openPanel(page, 'Mission');
    await expect(objective).toBeEnabled();
    await expect(page.getByLabel('Science score', { exact: true })).toHaveText('0');
    await expect(page.getByLabel('Samples inspected')).toHaveText('0');
  }
});

test('mission control sees energy use, separate recharging, and paused resource accounting', async ({ page }) => {
  await page.clock.install();
  await page.goto('/');
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText('160.0 / 160');
  await expect(page.getByLabel('Energy used', { exact: true })).toHaveText('0.0 units');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(42_500);
  await expect(page.getByLabel('Current action')).toHaveText('Recharge at base');
  await expect(page.getByLabel('Samples delivered')).toHaveText('1');
  await expect(page.getByLabel('Science score', { exact: true })).toHaveText('10');
  await expect(page.getByLabel('Cargo capacity')).toHaveText('0 / 2');
  await expect(page.getByLabel('Energy used', { exact: true })).toHaveText('16.0 units');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  const battery = await page.getByLabel('Battery charge', { exact: true }).textContent();
  const remaining = await page.getByLabel('Remaining expedition time').textContent();
  await page.clock.fastForward(10_000);
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText(battery!);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText(remaining!);
  await page.screenshot({ path: 'test-results/energy-recharge.png', fullPage: true });
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(4_000);
  await expect(page.getByLabel('Current action')).toContainText('Explore');
  await expect(page.getByLabel('Rover coordinates')).not.toHaveText('16.00 / 24.00');
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  const results = page.getByRole('region', { name: 'Expedition results' });
  await expect(results).toContainText('energy units used');
  await expect(results).toContainText('Baseline controller');
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText('160.0 / 160');
  await expect(page.getByLabel('Energy used', { exact: true })).toHaveText('0.0 units');
});

test('mission control edits instructions and inspects the baseline decision timeline', async ({ page }) => {
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  await page.goto('/');
  const instructions = page.getByRole('textbox', { name: 'Mission instructions' });
  await openPanel(page, 'Mission');
  await instructions.fill('Prioritize evidence of past water.');
  await page.getByRole('button', { name: 'Apply instructions' }).click();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  const timeline = page.getByRole('region', { name: 'Decision timeline' });
  await openPanel(page, 'Evidence');
  await timeline.getByText(/Decision 1 ·/).click();
  await expect(timeline).toContainText('Prioritize evidence of past water.');
  await expect(timeline).toContainText('Baseline controller');
  await expect(timeline).toContainText('No model probabilities or reasoning');
  await expect(timeline.getByRole('table', { name: 'Available actions' })).toContainText('Frontier 19 / 24');
  await expect(timeline.getByRole('table', { name: 'Observations used' })).toContainText('0.0 s');
  await expect(timeline.getByRole('table', { name: 'Rover memory used' })).toContainText('Base');
  await closePanel(page);
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.runFor(1_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await openPanel(page, 'Mission');
  await instructions.fill('Preserve energy for the return.');
  await page.getByRole('button', { name: 'Apply instructions' }).click();
  await expect(page.getByRole('combobox', { name: 'Scientific objective' })).toBeDisabled();
  await expect(page.getByLabel('Instruction status')).toContainText('next safe waypoint');
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.runFor(3_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await openPanel(page, 'Evidence');
  await timeline.getByText(/Decision 2 ·/).click();
  await expect(timeline.getByLabel('Decision 2 details')).toContainText('Preserve energy for the return.');
  await expect(timeline.getByLabel('Decision 2 details')).toContainText('Instructions changed');
  await timeline.getByText(/Decision 1 ·/).click();
  await expect(timeline.getByLabel('Decision 1 details')).toContainText('Prioritize evidence of past water.');
  await page.screenshot({ path: 'test-results/decisions.png', fullPage: true });
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await openPanel(page, 'Evidence');
  await expect(timeline).toContainText('Decisions will appear');
  await openPanel(page, 'Mission');
  await expect(instructions).toHaveValue('Preserve energy for the return.');
});

test('a pending scripted decision freezes time while camera and mission controls stay responsive', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') });
  await page.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
  // Substitute the controller only in this browser verification. The real UI and
  // expedition coordinator still own the timer, controls, and decision lifecycle.
  await page.route(/\/src\/main\.tsx(?:\?.*)?$/, route => route.fulfill({ contentType: 'text/javascript', body: `
    import React from '/node_modules/.vite/deps/react.js';
    import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';
    import { App } from '/src/ui/App.tsx';
    import { createExpedition } from '/src/simulation/expedition.ts';
    const createSession = () => createExpedition({ controller: { id: 'scripted', decide: input =>
      new Promise(resolve => setTimeout(() => resolve(input.candidates.find(action => action.kind === 'wait').id), 5000))
    } });
    ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App, { createSession }));
  ` }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await expect(page.getByLabel('Current action')).toHaveText('Awaiting decision');
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  const beforeOrbit = await scene.screenshot();
  const box = (await scene.locator('canvas').boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 160, box.y + box.height / 2 + 60, { steps: 8 });
  await page.mouse.up();
  await page.clock.runFor(300);
  expect(await scene.screenshot()).not.toEqual(beforeOrbit);
  await openPanel(page, 'Mission');
  await page.getByRole('textbox', { name: 'Mission instructions' }).fill('Preserve energy.');
  await page.getByRole('button', { name: 'Apply instructions' }).click();
  await page.getByRole('button', { name: '2×', exact: true }).click();
  await page.clock.runFor(6_000);
  await expect(page.getByLabel('Current action')).toHaveText('Awaiting decision');
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText('160.0 / 160');
  await expect(page.getByLabel('Rover coordinates')).toHaveText('16.00 / 24.00');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await page.clock.runFor(5_000);
  await expect(page.getByLabel('Current action')).toHaveText('Choice held before execution');
  await expect(page.getByRole('button', { name: 'Resume expedition' })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('18:00');
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.runFor(500);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('17:59');
});
