import { expect, test } from '@playwright/test';

test('mission control watches a 3D baseline expedition, orbits while paused, and finishes', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'RoverLab' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start expedition' })).toBeVisible();
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  await expect(scene.locator('canvas')).toBeVisible();
  await expect(page.getByText('Base · 01')).toBeVisible();
  await expect(page.getByText('Rover · 01', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('05:00');
  await page.screenshot({ path: 'test-results/expedition-ready.png', fullPage: true });
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.runFor(1_000);
  await expect(page.getByLabel('Current action')).toContainText('Frontier');
  await expect(page.getByLabel('Rover coordinates')).not.toHaveText('3.00 / 13.00');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  const pausedTime = await page.getByLabel('Remaining expedition time').textContent();
  const pausedPosition = await page.getByLabel('Rover coordinates').textContent();
  const box = (await scene.locator('canvas').boundingBox())!;
  const beforeOrbit = await scene.screenshot();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 170, box.y + box.height / 2 + 70, { steps: 12 });
  await page.mouse.up();
  await page.clock.runFor(1_000);
  expect(await scene.screenshot()).not.toEqual(beforeOrbit);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText(pausedTime!);
  await expect(page.getByLabel('Rover coordinates')).toHaveText(pausedPosition!);
  await page.getByRole('button', { name: '2×', exact: true }).click();
  await expect(page.getByRole('button', { name: '2×', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '4×', exact: true }).click();
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(76_000);
  await expect(page.getByRole('heading', { name: 'Time budget reached' })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('00:00');
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('05:00');
  await expect(page.getByLabel('Rover coordinates')).toHaveText('3.00 / 13.00');
  await expect(page.getByRole('button', { name: '1×', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  await expect(page.getByRole('heading', { name: 'Stopped by mission control' })).toBeVisible();
  await page.screenshot({ path: 'test-results/expedition.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('the scene reveals discoveries, distinguishes memory, and hides them again on reset', async ({ page }) => {
  await page.clock.install();
  await page.goto('/');
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  await expect(scene.locator('canvas')).toBeVisible();
  await expect(page.getByLabel('Terrain discovered')).toHaveText('29 / 399 cells');
  await expect(page.getByLabel('Samples discovered')).toHaveText('0');
  await expect(scene.getByText(/Sample [ABC]/)).toHaveCount(0);
  const beforeDiscovery = await scene.screenshot();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(10_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(scene.getByText('Sample A · In range', { exact: true })).toBeVisible();
  await expect(scene.getByText(/Sample [BC]/)).toHaveCount(0);
  await expect(page.getByLabel('Samples discovered')).toHaveText('1');
  await expect(page.getByLabel('Terrain discovered')).not.toHaveText('29 / 399 cells');
  expect(await scene.screenshot()).not.toEqual(beforeDiscovery);
  await page.screenshot({ path: 'test-results/perception-discovery.png', fullPage: true });
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(90_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(scene.getByText(/Sample A/)).toHaveCount(0);
  await expect(page.getByLabel('Sample A observation')).toContainText('Delivered');
  await expect(scene.getByText('Base · 01 · Remembered', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/perception-memory.png', fullPage: true });
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Terrain discovered')).toHaveText('29 / 399 cells');
  await expect(page.getByLabel('Samples discovered')).toHaveText('0');
  await expect(scene.getByText(/Sample [ABC]/)).toHaveCount(0);
});

test('mission control selects objectives, sees inspection and cargo, and scores delivery', async ({ page }) => {
  await page.clock.install();
  await page.goto('/');
  const objective = page.getByRole('combobox', { name: 'Scientific objective' });
  for (const [value, points] of [['past-water', '10'], ['unusual-minerals', '0']]) {
    await objective.selectOption(value!);
    await page.getByRole('button', { name: 'Start expedition' }).click();
    await expect(objective).toBeDisabled();
    await page.clock.fastForward(22_000);
    await expect(page.getByLabel('Current action')).toContainText('Inspect · Sample A');
    await expect(page.getByText('Properties unknown · Inspection required')).toBeVisible();
    await expect(page.getByLabel('Samples inspected')).toHaveText('0');
    await page.clock.fastForward(6_000);
    await expect(page.getByText(/Layered sediment/)).toBeVisible();
    await expect(page.getByLabel('Samples inspected')).toHaveText('1');
    await expect(page.getByLabel('Current action')).toContainText('Collect · Sample A');
    await page.clock.fastForward(4_000);
    await expect(page.getByLabel('Cargo capacity')).toHaveText('1 / 2');
    await expect(page.getByLabel('Science score', { exact: true })).toHaveText('0');
    await expect(page.getByLabel('Current action')).toHaveText('Return to base');
    await expect(page.getByRole('region', { name: 'Planetary scene' }).getByText(/Sample A/)).toHaveCount(0);
    await page.clock.fastForward(16_000);
    await expect(page.getByLabel('Cargo capacity')).toHaveText('0 / 2');
    await expect(page.getByLabel('Science score', { exact: true })).toHaveText(points!);
    await expect(page.getByLabel('Sample A observation')).toContainText('Delivered');
    await page.getByRole('button', { name: 'Stop expedition' }).click();
    await expect(page.getByRole('region', { name: 'Expedition results' })).toContainText(`${points} science points`);
    await expect(objective).toBeDisabled();
    await page.screenshot({ path: `test-results/science-${value}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Reset expedition' }).click();
    await expect(objective).toBeEnabled();
    await expect(page.getByLabel('Science score', { exact: true })).toHaveText('0');
    await expect(page.getByLabel('Samples inspected')).toHaveText('0');
  }
});

test('mission control sees energy use, separate recharging, and paused resource accounting', async ({ page }) => {
  await page.clock.install();
  await page.goto('/');
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText('100.0 / 100');
  await expect(page.getByLabel('Energy used', { exact: true })).toHaveText('0.0 units');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(47_500);
  await expect(page.getByLabel('Current action')).toHaveText('Recharge at base');
  await expect(page.getByLabel('Samples delivered')).toHaveText('1');
  await expect(page.getByLabel('Science score', { exact: true })).toHaveText('10');
  await expect(page.getByLabel('Cargo capacity')).toHaveText('0 / 2');
  await expect(page.getByLabel('Energy used', { exact: true })).toHaveText('16.0 units');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  const battery = await page.getByLabel('Battery charge', { exact: true }).textContent();
  const remaining = await page.getByLabel('Remaining expedition time').textContent();
  await page.clock.fastForward(10_000);
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText(battery!);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText(remaining!);
  await page.screenshot({ path: 'test-results/energy-recharge.png', fullPage: true });
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(4_000);
  await expect(page.getByLabel('Current action')).toContainText('Explore');
  await expect(page.getByLabel('Rover coordinates')).not.toHaveText('3.00 / 13.00');
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  const results = page.getByRole('region', { name: 'Expedition results' });
  await expect(results).toContainText('energy units used');
  await expect(results).toContainText('Baseline controller');
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Battery charge', { exact: true })).toHaveText('100.0 / 100');
  await expect(page.getByLabel('Energy used', { exact: true })).toHaveText('0.0 units');
});
