import { expect, test } from '@playwright/test';

test('mission control watches a 3D baseline expedition, orbits while paused, and finishes', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'RoverLab' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start expedition' })).toBeVisible();
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  await expect(scene.locator('canvas')).toBeVisible();
  await expect(page.getByText('Base · 01')).toBeVisible();
  await expect(page.getByText('Rover · 01', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('05:00');
  await page.screenshot({ path: 'test-results/expedition-ready.png', fullPage: true });
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.runFor(1_000);
  await expect(page.getByLabel('Current action')).toContainText('Near ridge');
  await expect(page.getByLabel('Rover coordinates')).not.toHaveText('3.00 / 13.00');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  const pausedTime = await page.getByLabel('Remaining expedition time').textContent();
  const pausedPosition = await page.getByLabel('Rover coordinates').textContent();
  const box = (await scene.locator('canvas').boundingBox())!;
  const beforeOrbit = await scene.screenshot();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 170, box.y + box.height / 2 + 70, { steps: 12 });
  await page.mouse.up();
  await page.clock.runFor(1_000);
  expect(await scene.screenshot()).not.toEqual(beforeOrbit);
  await expect(page.getByLabel('Remaining expedition time')).toHaveText(pausedTime!);
  await expect(page.getByLabel('Rover coordinates')).toHaveText(pausedPosition!);
  await page.getByRole('button', { name: '2×', exact: true }).click();
  await expect(page.getByRole('button', { name: '2×', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '4×', exact: true }).click();
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(76_000);
  await expect(page.getByRole('heading', { name: 'Time budget reached' })).toBeVisible();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('00:00');
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await expect(page.getByLabel('Remaining expedition time')).toHaveText('05:00');
  await expect(page.getByLabel('Rover coordinates')).toHaveText('3.00 / 13.00');
  await expect(page.getByRole('button', { name: '1×', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  await expect(page.getByRole('heading', { name: 'Stopped by mission control' })).toBeVisible();
  await page.screenshot({ path: 'test-results/expedition.png', fullPage: true });
  expect(errors).toEqual([]);
});
