import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';

for (const narrow of [false, true]) test(`authentic guide, evidence, usage, matched results and keyless entry (${narrow ? 'narrow' : 'desktop'})`, async ({ page }) => {
  test.setTimeout(90_000);
  if (narrow) await page.setViewportSize({ width: 390, height: 844 });
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  let calls = 0;
  await page.route('**/api/**', route => { calls++; return route.abort(); });
  await page.route('https://api.typesafe.ai/**', route => { calls++; return route.abort(); });
  await page.goto('/');
  await page.getByRole('button', { name: 'Start guided replay', exact: true }).click();
  await expect(page.getByRole('main', { name: 'Guided replay workspace' })).toBeVisible();
  await expect(page.getByLabel('Replay provider activity')).toContainText('0 new provider attempts');
  await expect(page.getByRole('heading', { name: '1. What the rover knows' })).toBeVisible();
  await page.clock.runFor(200);
  await page.screenshot({ path: `test-results/guided-entry-${narrow ? 'narrow' : 'desktop'}.png` });
  await page.getByRole('button', { name: 'Hide panel', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Guide panel' })).toBeHidden();
  await page.getByRole('button', { name: 'Evidence', exact: true }).click();
  await expect(page.getByLabel('Decision 2 details')).toBeVisible();
  await page.getByRole('button', { name: 'Usage', exact: true }).click();
  await expect(page.getByLabel('Historical inference usage')).toContainText('Confirmed provider attempts: 11');
  await expect(page.getByLabel('Historical inference usage')).toContainText('incomplete');
  await page.getByRole('button', { name: 'Record & replay', exact: true }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export expedition JSON', exact: true }).click();
  const exported = JSON.parse(await readFile(await (await download).path(), 'utf8'));
  expect(exported).toEqual(JSON.parse(await readFile('public/guided/jev.json', 'utf8')));
  await page.getByRole('button', { name: 'Replay expedition', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Expedition replay', exact: true })).toBeVisible();
  await page.clock.fastForward(150_000);
  await expect(page.getByRole('region', { name: 'Expedition replay', exact: true }).getByRole('status')).toHaveText('Replay complete');
  await page.getByRole('button', { name: 'Guide', exact: true }).click();
  await page.getByRole('button', { name: 'Next guide step' }).click();
  await expect(page.getByRole('heading', { name: '2. Jev chooses' })).toBeVisible();
  await page.getByRole('button', { name: 'Next guide step' }).click();
  await expect(page.getByRole('heading', { name: '3. A baseline alternative' })).toBeVisible();
  await page.getByRole('button', { name: 'Next guide step' }).click();
  await page.clock.fastForward(10_000);
  await expect(page.getByLabel('Guide consequences')).toContainText('142.0');
  await page.getByRole('button', { name: 'Next guide step' }).click();
  await expect(page.getByRole('heading', { name: '5. Original cost and failure' })).toBeVisible();
  await page.getByRole('button', { name: 'Next guide step' }).click();
  await expect(page.getByRole('heading', { name: '6. Compare actual outcomes' })).toBeVisible();
  await page.getByRole('button', { name: 'Matched results', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Expedition comparison' })).toContainText('Full expedition unfinished');
  await page.screenshot({ path: `test-results/guided-${narrow ? 'narrow' : 'desktop'}.png` });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Finish guide', exact: true }).click();
  await page.getByRole('button', { name: 'Start keyless baseline', exact: true }).click();
  await page.clock.fastForward(20_000);
  await expect(page.getByLabel('Live provider attempts')).toHaveText('0');
  await expect(page.getByRole('button', { name: 'Pause expedition', exact: true })).toBeVisible();
  expect(calls).toBe(0);
});


test('live setup exposes limits before inference and missing guide assets leave keyless entry usable', async ({ page }) => {
  let calls = 0;
  await page.route('**/api/**', route => { calls++; return route.abort(); });
  await page.route('**/guided/jev.json', route => route.fulfill({ status: 404, body: 'Unavailable' }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start guided replay', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('could not be loaded or validated');
  await page.getByRole('button', { name: 'Set up live Jev', exact: true }).click();
  await expect(page.getByLabel('Live Jev setup')).toContainText('TYPESAFE_API_KEY');
  await expect(page.getByRole('spinbutton', { name: 'Provider-attempt limit', exact: true })).toHaveValue('250');
  await expect(page.getByRole('spinbutton', { name: 'Estimated-cost limit in USD', exact: true })).toHaveValue('0.1');
  expect(calls).toBe(0);
});

test('loading a guided record cannot hide a newly started live expedition', async ({ page }) => {
  let release!: () => void;
  const gate = new Promise<void>(resolve => { release = resolve; });
  let calls = 0;
  await page.route('**/api/**', route => { calls++; return route.abort(); });
  await page.route('**/guided/jev.json', async route => { await gate; await route.continue(); });
  await page.goto('/');
  await page.getByRole('button', { name: 'Set up live Jev', exact: true }).click();
  await page.getByRole('button', { name: 'Close panel', exact: true }).click();
  await page.getByRole('button', { name: 'Start guided replay', exact: true }).click();
  await expect(page.locator('main')).toHaveAttribute('inert', '');
  await expect(page.getByRole('status')).toContainText('Loading and validating');
  release();
  await expect(page.getByRole('main', { name: 'Guided replay workspace' })).toBeVisible();
  expect(calls).toBe(0);
});
