import { expect, test } from '@playwright/test';
import { openPanel } from './panels';

test('mission control runs the example schedule in layout A and inspects its recorded requests', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') });
  await page.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
  let calls = 0;
  await page.route('**/api/**', route => { calls++; return route.abort(); });
  await page.goto('/');
  await openPanel(page, 'Mission');
  const schedule = page.getByRole('region', { name: 'Intervention schedule', exact: true });
  await expect(schedule.getByRole('button', { name: 'Use example schedule' })).toBeVisible();
  await schedule.getByRole('button', { name: 'Use example schedule' }).focus();
  await page.keyboard.press('Enter');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('complementary', { name: 'Expedition panel' })).toBeHidden();
  await openPanel(page, 'Mission');
  await expect(schedule).toContainText('01:00.0');
  await expect(schedule).toContainText('06:00.0');
  await expect(schedule).toContainText('28 / 24');
  await expect(page.getByRole('button', { name: 'Introduce dust storm' })).toBeDisabled();
  await page.getByRole('button', { name: '4×', exact: true }).click();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(15_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await openPanel(page, 'Mission');
  await expect(schedule).toContainText('Requested at 01:00.0');
  const before = await schedule.textContent();
  await page.clock.fastForward(60_000);
  await expect(schedule).toHaveText(before!);
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(75_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(schedule.getByText('Scheduled · Requested at 06:00.0', { exact: true })).toHaveCount(2);
  await schedule.getByRole('listitem').last().scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/intervention-schedule.png' });
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  await openPanel(page, 'Saved expeditions');
  await page.getByRole('button', { name: /Open expedition/ }).click();
  const saved = page.getByRole('region', { name: 'Saved expedition', exact: true });
  await expect(saved.getByRole('region', { name: 'Intervention schedule', exact: true })).toContainText('Requested at 06:00.0');
  await saved.getByRole('button', { name: 'Replay expedition', exact: true }).click();
  await page.clock.fastForward(360_000);
  const replay = saved.getByRole('region', { name: 'Expedition replay', exact: true });
  await expect(replay.getByRole('status')).toHaveText('Replay complete');
  await expect(replay.getByRole('region', { name: 'Intervention schedule', exact: true })).toContainText('Requested at 06:00.0');
  expect(calls).toBe(0);
});

test('manual storm and mission history stays readable on a narrow screen and after reload', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') });
  await page.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.runFor(1_300);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await openPanel(page, 'Mission');
  await page.getByRole('button', { name: 'Introduce dust storm' }).click();
  await page.getByRole('textbox', { name: 'Mission instructions' }).fill('Return with evidence.');
  await page.getByRole('button', { name: 'Apply instructions' }).click();
  const schedule = page.getByRole('region', { name: 'Intervention schedule', exact: true });
  await expect(schedule.getByText('Manual · Requested at 00:01.3', { exact: true })).toHaveCount(2);
  await expect(schedule).toContainText('Waiting for a safe action boundary');
  await expect(schedule).toContainText('Return with evidence.');
  await schedule.getByRole('listitem').last().scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/intervention-history-narrow.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await schedule.getByText('Schedule rules and provenance', { exact: true }).focus();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('navigation', { name: 'Expedition panels' }).getByRole('button', { name: 'Mission', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Stop expedition' }).click();
  await page.reload();
  await openPanel(page, 'Saved expeditions');
  await page.getByRole('button', { name: /Open expedition/ }).click();
  const archived = page.getByRole('region', { name: 'Saved expedition', exact: true }).getByRole('region', { name: 'Intervention schedule', exact: true });
  await expect(archived.getByText('Manual · Requested at 00:01.3', { exact: true })).toHaveCount(2);
  await expect(archived).toContainText('Not applied before expedition ended');
});
