import { openPanel } from './panels';
import { expect, test } from '@playwright/test';
import type { ExpeditionSession } from '../src/simulation/expedition';

type SessionWindow = Window & { expedition: ExpeditionSession; reference: ExpeditionSession };

// Drive the real App and expose only the public session boundary for comparison.
const appEntry = `
  import React from '/node_modules/.vite/deps/react.js';
  import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';
  import { App } from '/src/ui/App.tsx';
  import { createExpedition } from '/src/simulation/expedition.ts';
  window.expedition = createExpedition();
  window.reference = createExpedition();
  ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App, { createSession: () => window.expedition }));
`;

test('observation controls reveal only the debug scene and preserve controller inputs and a complete expedition', async ({ page }) => {
  // Compare two complete eighteen-minute histories alongside the WebGL controls.
  test.setTimeout(60_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') });
  await page.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
  await page.route(/\/src\/main\.tsx(?:\?.*)?$/, route => route.fulfill({ contentType: 'text/javascript', body: appEntry }));
  await page.goto('/');
  await page.clock.runFor(100);
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  const debug = page.getByRole('checkbox', { name: 'Full-world debugging view' });
  const coverage = page.getByRole('checkbox', { name: 'Sensor coverage' });
  const follow = page.getByRole('button', { name: 'Follow rover', exact: true });
  const orbit = page.getByRole('button', { name: 'Orbit camera', exact: true });
  await expect(orbit).toHaveAttribute('aria-pressed', 'true');
  await expect(debug).not.toBeChecked();
  await expect(coverage).toBeChecked();
  await expect(scene.getByLabel('Sensor coverage radius')).toHaveText('3 cells');
  await expect(scene.getByText(/Sample [ABC]/)).toHaveCount(0);
  await debug.check();
  await page.clock.runFor(100);
  await expect(scene.getByText('Full-world view · DEBUG', { exact: true })).toBeVisible();
  for (const label of ['A', 'B', 'C']) await expect(scene.getByText(`Sample ${label} · Hidden from rover`, { exact: true })).toBeVisible();
  await expect(page.getByLabel('Samples discovered')).toHaveText('0');
  await expect(page.getByLabel('Terrain discovered')).toHaveText('29 / 1596 cells');
  await openPanel(page, 'Mission');
  await page.getByRole('button', { name: 'Introduce dust storm' }).click();
  await page.evaluate(() => (window as unknown as SessionWindow).reference.dispatch({ type: 'introduce-storm' }));
  await page.clock.runFor(100);
  await expect(scene.getByText('Dust storm · Hidden from rover', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Dust storm controls' })).toContainText('The rover has not detected it');
  await page.screenshot({ path: 'test-results/observation-full-world.png', fullPage: true });
  await debug.uncheck();
  await page.clock.runFor(100);
  await expect(scene.getByText(/Sample [ABC]|Dust storm/)).toHaveCount(0);
  await coverage.uncheck();
  await expect(scene.getByLabel('Sensor coverage radius')).toHaveCount(0);
  await follow.click();
  await page.clock.runFor(300);
  await expect(follow).toHaveAttribute('aria-pressed', 'true');
  await expect(scene.getByText('Rover · 01', { exact: true })).toBeVisible();
  await coverage.check();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.evaluate(() => (window as unknown as SessionWindow).reference.dispatch({ type: 'start' }));
  await page.clock.runFor(1_000);
  await page.evaluate(() => (window as unknown as SessionWindow).reference.advanceWallTime(1_000));
  await expect(page.getByLabel('Rover coordinates')).not.toHaveText('16.00 / 24.00');
  await orbit.click();
  await follow.click();
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await page.evaluate(() => (window as unknown as SessionWindow).reference.dispatch({ type: 'pause' }));
  const paused = await page.evaluate(() => (window as unknown as SessionWindow).expedition.getSnapshot());
  await page.clock.runFor(1_000);
  const before = await scene.locator('canvas').screenshot();
  await coverage.uncheck();
  await page.clock.runFor(200);
  expect(await scene.locator('canvas').screenshot()).not.toEqual(before);
  await coverage.check();
  await debug.check();
  await page.clock.runFor(100);
  await orbit.click();
  await follow.click();
  await page.clock.runFor(300);
  expect(await page.evaluate(() => (window as unknown as SessionWindow).expedition.getSnapshot())).toEqual(paused);
  await page.screenshot({ path: 'test-results/observation-follow.png', fullPage: true });
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.evaluate(() => (window as unknown as SessionWindow).reference.dispatch({ type: 'resume' }));
  await page.clock.fastForward(25_900);
  await page.clock.runFor(100);
  await page.evaluate(() => (window as unknown as SessionWindow).reference.advanceWallTime(26_000));
  await expect(scene.getByText(/Sample A/)).toHaveCount(0);
  await debug.uncheck();
  await orbit.click();
  await page.clock.fastForward(1_053_000);
  await page.evaluate(() => (window as unknown as SessionWindow).reference.advanceWallTime(1_053_000));
  await expect(page.getByRole('heading', { name: 'Time budget reached' })).toBeVisible();
  const comparison = await page.evaluate(() => {
    const { expedition, reference } = window as unknown as SessionWindow;
    return { actual: expedition.getRecord(), expected: reference.getRecord(), decisions: expedition.getDecisions(), referenceDecisions: reference.getDecisions() };
  });
  expect(comparison.decisions).toEqual(comparison.referenceDecisions);
  expect(comparison.actual).toEqual(comparison.expected);
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await debug.check();
  await page.clock.runFor(100);
  await expect(scene.getByText('Sample A · Hidden from rover', { exact: true })).toBeVisible();
  await expect(scene.getByText(/Dust storm/)).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('follow keeps the moving rover in view, supports paused inspection, and restores the orbit perspective', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') });
  await page.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
  await page.goto('/');
  await page.clock.runFor(100);
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  const canvas = scene.locator('canvas');
  const follow = page.getByRole('button', { name: 'Follow rover', exact: true });
  const orbit = page.getByRole('button', { name: 'Orbit camera', exact: true });
  const box = (await canvas.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 100, box.y + box.height / 2 + 40, { steps: 8 });
  await page.mouse.up();
  await page.clock.runFor(100);
  const orbitImage = await canvas.screenshot({ path: 'test-results/observation-orbit-before.png' });
  const landmarks = [scene.getByText('Rover · 01', { exact: true }), scene.getByText('Base · 01', { exact: true })];
  const orbitLandmarks = await Promise.all(landmarks.map(label => label.boundingBox()));
  await follow.click();
  await page.clock.runFor(100);
  expect((await canvas.screenshot()).equals(orbitImage)).toBe(false);
  await orbit.click();
  await page.clock.runFor(100);
  await canvas.screenshot({ path: 'test-results/observation-orbit-restored.png' });
  for (const [index, label] of landmarks.entries()) {
    const restored = (await label.boundingBox())!;
    expect(Math.abs(restored.x - orbitLandmarks[index]!.x)).toBeLessThan(0.5);
    expect(Math.abs(restored.y - orbitLandmarks[index]!.y)).toBeLessThan(0.5);
  }
  await follow.click();
  await page.clock.runFor(100);
  const roverLabel = scene.getByText('Rover · 01', { exact: true });
  const initial = (await roverLabel.boundingBox())!;
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.runFor(1_000);
  await canvas.screenshot({ path: 'test-results/rover-moving-01.png' });
  await page.clock.fastForward(8_900);
  await page.clock.runFor(100);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await page.clock.runFor(2_000);
  const followed = (await roverLabel.boundingBox())!;
  expect(Math.abs(followed.x - initial.x)).toBeLessThan(2);
  expect(Math.abs(followed.y - initial.y)).toBeLessThan(2);
  await expect(page.getByLabel('Rover coordinates')).toHaveText('18.50 / 24.00');
  const paused = await canvas.screenshot({ path: 'test-results/rover-moving-02.png' });
  await page.clock.runFor(1_000);
  expect((await canvas.screenshot()).equals(paused)).toBe(true);
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 120, box.y + box.height / 2 + 20, { steps: 8 });
  await page.mouse.up();
  await page.clock.runFor(100);
  expect((await canvas.screenshot()).equals(paused)).toBe(false);
  await page.mouse.wheel(0, -250);
  await page.clock.runFor(100);
  await expect(roverLabel).toBeVisible();
  await expect(page.getByLabel('Rover coordinates')).toHaveText('18.50 / 24.00');
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await page.clock.runFor(100);
  await expect(follow).toHaveAttribute('aria-pressed', 'true');
  await expect(roverLabel).toBeVisible();
  await expect(page.getByLabel('Rover coordinates')).toHaveText('16.00 / 24.00');
});

test('sensor coverage follows storm range changes and observation controls stay responsive during a pending decision', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') });
  await page.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
  await page.route(/\/src\/main\.tsx(?:\?.*)?$/, route => route.fulfill({ contentType: 'text/javascript', body: `
    import React from '/node_modules/.vite/deps/react.js';
    import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';
    import { App } from '/src/ui/App.tsx';
    import { createExpedition } from '/src/simulation/expedition.ts';
    import { authoredScenario } from '/src/simulation/scenario.ts';
    window.expedition = createExpedition({
      scenario: { ...authoredScenario, dustStorm: { ...authoredScenario.dustStorm, position: authoredScenario.base, durationMs: 2000 } },
      controller: { id: 'scripted', decide: input => new Promise(resolve => setTimeout(() => resolve(input.candidates.find(action => action.kind === 'wait').id), 5000)) },
    });
    ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App, { createSession: () => window.expedition }));
  ` }));
  await page.goto('/');
  await page.clock.runFor(100);
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  const coverage = page.getByRole('checkbox', { name: 'Sensor coverage' });
  const debug = page.getByRole('checkbox', { name: 'Full-world debugging view' });
  await page.getByRole('button', { name: 'Follow rover', exact: true }).click();
  await page.clock.runFor(100);
  await expect(scene.getByLabel('Sensor coverage radius')).toHaveText('3 cells');
  await openPanel(page, 'Mission');
  await page.getByRole('button', { name: 'Introduce dust storm' }).click();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await expect(page.getByLabel('Current action')).toHaveText('Awaiting decision');
  await expect(scene.getByLabel('Sensor coverage radius')).toHaveText('1.5 cells');
  const pending = await page.evaluate(() => (window as unknown as SessionWindow).expedition.getSnapshot());
  const decisions = await page.evaluate(() => (window as unknown as SessionWindow).expedition.getDecisions());
  await page.clock.runFor(300);
  const withCoverage = await scene.locator('canvas').screenshot();
  await coverage.uncheck();
  await page.clock.runFor(100);
  expect(await scene.locator('canvas').screenshot()).not.toEqual(withCoverage);
  await coverage.check();
  await debug.check();
  await page.getByRole('button', { name: 'Orbit camera', exact: true }).click();
  await page.clock.runFor(100);
  await expect(scene.getByText('Sample C · Hidden from rover', { exact: true })).toBeVisible();
  await debug.uncheck();
  await page.getByRole('button', { name: 'Follow rover', exact: true }).click();
  await page.clock.runFor(100);
  expect(await page.evaluate(() => (window as unknown as SessionWindow).expedition.getSnapshot())).toEqual(pending);
  expect(await page.evaluate(() => (window as unknown as SessionWindow).expedition.getDecisions())).toEqual(decisions);
  await expect(page.getByLabel('Storm time remaining')).toHaveText('2.0 s');
  await scene.screenshot({ path: 'test-results/observation-reduced-sensors.png' });
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await page.clock.runFor(5_000);
  await expect(page.getByLabel('Current action')).toContainText('Wait');
  await expect(scene.getByLabel('Sensor coverage radius')).toHaveText('1.5 cells');
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.runFor(2_000);
  await expect(scene.getByLabel('Sensor coverage radius')).toHaveText('3 cells');
  await expect(scene.getByText(/Dust storm/)).toHaveCount(0);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await page.clock.runFor(100);
  await scene.screenshot({ path: 'test-results/observation-restored-sensors.png' });
});
