import { openPanel } from './panels';
import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';

test('saved and imported expeditions replay with independent controls and unchanged records', async ({ page, browser }) => {
  // Replay the full eighteen-minute history in both contexts and exchange its JSON.
  test.setTimeout(90_000);
  await page.clock.install();
  await page.goto('/');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(90_000);
  await openPanel(page, 'Mission');
  await page.getByRole('button', { name: 'Introduce dust storm' }).click();
  await page.getByRole('textbox', { name: 'Mission instructions' }).fill('Avoid costly crossings.');
  await page.getByRole('button', { name: 'Apply instructions' }).click();
  await page.clock.fastForward(990_000);
  await openPanel(page, 'Saved expeditions');
  await page.getByRole('button', { name: /Open expedition/ }).click();
  const results = await page.getByRole('region', { name: 'Expedition results' }).textContent();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export expedition JSON' }).click();
  const json = await readFile((await (await download).path())!, 'utf8');
  const source = JSON.parse(json);

  await page.getByRole('button', { name: 'Replay expedition', exact: true }).click();
  const replay = page.getByRole('region', { name: 'Expedition replay', exact: true });
  await expect(replay).toContainText('REPLAY · RECORDED EXPEDITION');
  await expect(replay.getByRole('region', { name: 'Planetary scene' })).toBeVisible();
  await page.clock.fastForward(10_000);
  await replay.getByRole('button', { name: 'Pause replay' }).click();
  const coordinates = await replay.getByLabel('Replay rover coordinates').textContent();
  const elapsed = await replay.getByLabel('Replay elapsed time').textContent();
  await page.clock.fastForward(60_000);
  await expect(replay.getByLabel('Replay elapsed time')).toHaveText(elapsed!);
  await expect(replay.getByLabel('Replay rover coordinates')).toHaveText(coordinates!);
  await replay.getByRole('button', { name: 'Follow rover' }).click();
  await replay.getByText(/Decision 1 ·/).click();
  await expect(replay.getByRole('table', { name: 'Available actions' })).toBeVisible();
  await replay.getByRole('group', { name: 'Replay speed' }).getByRole('button', { name: '4×' }).click();
  await page.screenshot({ path: 'test-results/replay-paused.png', fullPage: true });
  await replay.getByRole('button', { name: 'Resume replay' }).click();
  await page.clock.fastForward(270_000);
  await expect(replay.getByRole('status')).toHaveText('Replay complete');
  await expect(replay.getByLabel('Replay science score')).toHaveText(String(source.results.scienceScore));
  await expect(page.getByRole('region', { name: 'Expedition results' })).toHaveText(results!);
  await openPanel(page, 'Saved expeditions');
  await expect(page.getByRole('button', { name: /Open expedition/ })).toHaveCount(1);

  const context = await browser.newContext({ baseURL: 'http://127.0.0.1:4173' });
  const viewer = await context.newPage();
  await viewer.clock.install();
  let inferenceRequests = 0;
  await viewer.route('**/api/**', route => { inferenceRequests++; return route.abort(); });
  await viewer.goto('/');
  const file = { name: 'expedition.json', mimeType: 'application/json', buffer: Buffer.from(json) };
  await openPanel(viewer, 'Saved expeditions');
  await viewer.getByLabel('Import expedition JSON').setInputFiles(file);
  await viewer.getByRole('button', { name: 'Replay expedition', exact: true }).click();
  await viewer.clock.fastForward(5_000);
  await viewer.getByRole('button', { name: 'Stop replay' }).click();
  await expect(viewer.getByRole('status')).toHaveText('Replay stopped');
  await viewer.clock.fastForward(60_000);
  const copy = viewer.waitForEvent('download');
  await viewer.getByRole('button', { name: 'Export expedition JSON' }).click();
  expect(JSON.parse(await readFile((await (await copy).path())!, 'utf8'))).toEqual(source);
  await viewer.getByRole('button', { name: 'Restart replay' }).click();
  await viewer.getByRole('group', { name: 'Replay speed' }).getByRole('button', { name: '2×' }).click();
  await viewer.clock.fastForward(540_000);
  await expect(viewer.getByRole('status')).toHaveText('Replay complete');
  await expect(viewer.getByRole('region', { name: 'Expedition results' })).toHaveText(results!);

  const unsupported = { ...source, id: crypto.randomUUID(), startingConditions: { ...source.startingConditions, fixedStepMs: 50 } };
  await openPanel(viewer, 'Saved expeditions');
  await viewer.getByLabel('Import expedition JSON').setInputFiles({ ...file, buffer: Buffer.from(JSON.stringify(unsupported)) });
  await viewer.getByRole('button', { name: 'Replay expedition', exact: true }).click();
  await expect(viewer.getByRole('alert')).toContainText('Cannot replay this expedition');
  await expect(viewer.getByRole('region', { name: 'Expedition replay', exact: true })).toHaveCount(0);
  await expect(viewer.getByRole('button', { name: /Open expedition/ })).toHaveCount(2);
  expect(inferenceRequests).toBe(0);
  await context.close();
});
