import { openPanel, closePanel } from './panels';
import { expect, test } from '@playwright/test';

test('mission control introduces a hidden storm, observes detection, and freezes its visible duration while orbiting', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto('/');
  const introduce = page.getByRole('button', { name: 'Introduce dust storm' });
  await openPanel(page, 'Mission');
  await expect(introduce).toBeEnabled({ timeout: 1_000 });
  await introduce.click();
  const panel = page.getByRole('region', { name: 'Dust storm controls' });
  const scene = page.getByRole('region', { name: 'Planetary scene' });
  await expect(panel).toContainText('The rover has not detected it');
  await expect(scene.getByText(/Dust storm/)).toHaveCount(0);
  await expect(page.getByLabel('Storm time remaining')).toHaveCount(0);
  await expect(introduce).toBeDisabled();
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await openPanel(page, 'Mission');
  await expect(introduce).toBeEnabled();
  await page.getByRole('combobox', { name: 'Scientific objective' }).selectOption('unusual-minerals');
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await page.clock.fastForward(90_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await openPanel(page, 'Mission');
  await introduce.click();
  await expect(panel).toContainText('Detected');
  await expect(scene.getByText(/Dust storm/)).toBeVisible();
  await expect(page.getByLabel('Storm time remaining')).toHaveText('45.0 s');
  const before = await scene.screenshot();
  const box = (await scene.locator('canvas').boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 130, box.y + box.height / 2 + 50, { steps: 8 });
  await page.mouse.up();
  await page.clock.runFor(1_000);
  expect(await scene.screenshot()).not.toEqual(before);
  await expect(page.getByLabel('Storm time remaining')).toHaveText('45.0 s');
  await page.screenshot({ path: 'test-results/storm-detected.png', fullPage: true });
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(5_000);
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  const timeline = page.getByRole('region', { name: 'Decision timeline' });
  await openPanel(page, 'Evidence');
  await timeline.locator('summary').last().click();
  await expect(timeline).toContainText('Dust storm');
  await closePanel(page);
  await page.getByRole('button', { name: 'Resume expedition' }).click();
  await page.clock.fastForward(41_000);
  await openPanel(page, 'Mission');
  await expect(panel).toContainText('Known dust storm expired');
  await expect(scene.getByText(/Dust storm/)).toHaveCount(0);
  await page.getByRole('button', { name: 'Reset expedition' }).click();
  await openPanel(page, 'Mission');
  await expect(introduce).toBeEnabled();
  await expect(panel).not.toContainText('Detected');
  expect(errors).toEqual([]);
});
